//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer FoveationVars
// {
//
//   uint2 targetResolution;            // Offset:    0 Size:     8 [unused]
//   uint2 optimizedResolution;         // Offset:    8 Size:     8 [unused]
//   float2 eyeSizeRatio;               // Offset:   16 Size:     8
//   float2 centerSize;                 // Offset:   24 Size:     8
//   float2 centerShift;                // Offset:   32 Size:     8
//   float2 edgeRatio;                  // Offset:   40 Size:     8
//   float2 eyeShift;                   // Offset:   48 Size:     8
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// trilinearSampler                  sampler      NA          NA             s0      1 
// compositionTexture                texture  float4          2d             t0      1 
// FoveationVars                     cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// TEXCOORD                 0   xy          0     NONE   float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[4], immediateIndexed
dcl_sampler s0, mode_default
dcl_resource_texture2d (float,float,float,float) t0
dcl_input_ps linear v0.xy
dcl_output o0.xyzw
dcl_temps 5
add r0.x, cb0[2].x, -cb0[3].x
add r0.yz, cb0[2].yyxy, cb0[3].yyxy
lt r0.w, l(0.500000), v0.x
movc r1.xyzw, r0.wwww, r0.xyxy, r0.zyzy
and r0.x, r0.w, l(0x3f800000)
add r1.xyzw, r1.xyzw, l(1.000000, 1.000000, -1.000000, -1.000000)
add r2.xyzw, -cb0[1].zwzw, l(1.000000, 1.000000, 1.000000, 1.000000)
mul r2.xyzw, r2.xyzw, l(0.500000, 0.500000, 0.500000, 0.500000)
add r0.yz, cb0[2].zzwz, l(0.000000, -1.000000, -1.000000, 0.000000)
mul r3.xy, r2.zwzz, r0.yzyy
mul r2.xyzw, r1.xyzw, r2.xyzw
mul r1.xy, r1.xyxx, r3.xyxx
div r1.xy, r1.xyxx, cb0[2].zwzz
mad r0.yz, r0.yyzy, cb0[1].zzwz, l(0.000000, 1.000000, 1.000000, 0.000000)
mad r0.w, -v0.x, l(2.000000), l(1.000000)
mad r0.w, r0.x, r0.w, v0.x
add r3.y, r0.w, r0.w
mov r3.z, v0.y
div r1.zw, r3.yyyz, cb0[1].xxxy
mul r3.xy, r0.yzyy, r1.zwzz
div r3.zw, r3.xxxy, cb0[2].zzzw
add r1.xy, r1.xyxx, r3.zwzz
div r2.xyzw, r2.xyzw, r0.yzyz
div r3.zw, r1.zzzw, r2.xxxy
add r4.xy, -r3.zwzz, l(1.000000, 1.000000, 0.000000, 0.000000)
mul r3.xy, r3.xyxx, r4.xyxx
mad r3.xy, r3.zwzz, r1.xyxx, r3.xyxx
lt r3.zw, r2.xxxy, r1.zzzw
add r2.zw, r2.zzzw, l(0.000000, 0.000000, 1.000000, 1.000000)
lt r2.xy, r1.zwzz, r2.xyxx
and r2.xy, r2.xyxx, l(0x3f800000, 0x3f800000, 0, 0)
lt r4.xy, r1.zwzz, r2.zwzz
and r3.zw, r3.zzzw, r4.xxxy
and r3.zw, r3.zzzw, l(0, 0, 0x3f800000, 0x3f800000)
mul r3.zw, r1.xxxy, r3.zzzw
mad r2.xy, r2.xyxx, r3.xyxx, r3.zwzz
add r3.xy, r1.zwzz, l(-1.000000, -1.000000, 0.000000, 0.000000)
mad r0.yz, r3.xxyx, r0.yyzy, l(0.000000, 1.000000, 1.000000, 0.000000)
add r3.xy, -r2.zwzz, l(1.000000, 1.000000, 0.000000, 0.000000)
lt r2.zw, r2.zzzw, r1.zzzw
add r1.zw, -r1.zzzw, l(0.000000, 0.000000, 1.000000, 1.000000)
div r1.zw, r1.zzzw, r3.xxxy
and r2.zw, r2.zzzw, l(0, 0, 0x3f800000, 0x3f800000)
add r3.xy, -r1.zwzz, l(1.000000, 1.000000, 0.000000, 0.000000)
mul r0.yz, r0.yyzy, r3.xxyx
mad r0.yz, r1.zzwz, r1.xxyx, r0.yyzy
mad r1.yz, r2.zzwz, r0.yyzy, r2.xxyx
add r0.y, -r1.y, l(1.000000)
mul r0.x, r0.y, r0.x
mad r1.x, r1.y, l(0.500000), r0.x
sample_indexable(texture2d)(float,float,float,float) o0.xyzw, r1.xzxx, t0.xyzw, s0
ret 
// Approximately 52 instruction slots used
